Repository Turing-mentos/Turing-BE, pull requests merged in 2024-07, with the labels that each got.

#23 Fix: ui 변경에 따른 erd 필드 추가
  src/main/java/turing/turing/domain/studyRoom/StudyRoom.java
Labels: 🛠️ Fix

#21 [Feat] 과외공간 도메인 기능 구현
  src/main/java/turing/turing/domain/code/ConnectionCode.java
  src/main/java/turing/turing/domain/code/ConnectionCodeRepository.java
  src/main/java/turing/turing/domain/question/Question.java
  src/main/java/turing/turing/domain/schedule/ScheduleRepository.java
  src/main/java/turing/turing/domain/student/Student.java
  src/main/java/turing/turing/domain/student/StudentRepository.java
  src/main/java/turing/turing/domain/studyRoom/StudyRoom.java
  src/main/java/turing/turing/domain/studyRoom/StudyRoomController.java
  src/main/java/turing/turing/domain/studyRoom/StudyRoomRepository.java
  src/main/java/turing/turing/domain/studyRoom/StudyRoomService.java
  src/main/java/turing/turing/domain/studyRoom/dto/DetailedStudyRoomResDto.java
  src/main/java/turing/turing/domain/studyRoom/dto/StudyRoomCreateReqDto.java
  src/main/java/turing/turing/domain/studyRoom/dto/StudyRoomResDto.java
  src/main/java/turing/turing/domain/studyRoom/dto/StudyRoomUpdateReqDto.java
  src/main/java/turing/turing/domain/studyTime/StudyTime.java
  src/main/java/turing/turing/domain/studyTime/StudyTimeRepository.java
  src/main/java/turing/turing/domain/studyTime/dto/StudyTimeReqDto.java
  src/main/java/turing/turing/domain/studyTime/dto/StudyTimeResDto.java
  src/main/java/turing/turing/domain/teacher/Teacher.java
  src/main/java/turing/turing/domain/teacher/TeacherRepository.java
Labels: ⭐️ Feature

#26 [Feat] 시급 필드 추가에 따른 수정 사항 반영
  src/main/java/turing/turing/domain/studyRoom/StudyRoom.java
  src/main/java/turing/turing/domain/studyRoom/dto/DetailedStudyRoomResDto.java
  src/main/java/turing/turing/domain/studyRoom/dto/StudyRoomCreateReqDto.java
Labels: ⭐️ Feature

#22 [Feat] 애플 로그인 구현
  build.gradle
  src/main/java/turing/turing/domain/Member.java
  src/main/java/turing/turing/domain/Provider.java
  src/main/java/turing/turing/domain/Role.java
  src/main/java/turing/turing/domain/auth/AuthController.java
  src/main/java/turing/turing/domain/auth/AuthService.java
  src/main/java/turing/turing/domain/auth/CustomUserDetailService.java
  src/main/java/turing/turing/domain/auth/CustomUserDetails.java
  src/main/java/turing/turing/domain/auth/apple/AppleClient.java
  src/main/java/turing/turing/domain/auth/apple/ApplePublicKey.java
  src/main/java/turing/turing/domain/auth/apple/ApplePublicKeyGenerator.java
  src/main/java/turing/turing/domain/auth/apple/ApplePublicKeys.java
  src/main/java/turing/turing/domain/auth/apple/AppleTokenParser.java
  src/main/java/turing/turing/domain/auth/apple/VerifyAppleRequest.java
  src/main/java/turing/turing/domain/auth/dto/LoginRequest.java
  src/main/java/turing/turing/domain/auth/dto/LoginResponse.java
  src/main/java/turing/turing/domain/auth/dto/TokenReIssueRequest.java
  src/main/java/turing/turing/domain/auth/jwt/JwtTokenProvider.java
  src/main/java/turing/turing/domain/auth/jwt/TokenResponse.java
  src/main/java/turing/turing/domain/student/Student.java
  src/main/java/turing/turing/domain/student/StudentRepository.java
  src/main/java/turing/turing/domain/teacher/Teacher.java
  src/main/java/turing/turing/domain/teacher/TeacherController.java
  src/main/java/turing/turing/domain/teacher/TeacherRepository.java
  src/main/java/turing/turing/domain/teacher/TeacherService.java
  src/main/java/turing/turing/domain/teacher/dto/SignUpResponse.java
  src/main/java/turing/turing/domain/teacher/dto/TeacherSignUpRequest.java
  src/main/java/turing/turing/global/config/OpenFeignConfig.java
  src/main/java/turing/turing/global/config/SecurityConfig.java
  src/main/java/turing/turing/global/security/JwtAuthenticationFilter.java
  src/main/resources/application.yml
Labels: ⭐️ Feature

#31 [Fix] Security Config 수정
  src/main/java/turing/turing/domain/auth/AuthController.java
  src/main/java/turing/turing/domain/auth/AuthService.java
  src/main/java/turing/turing/domain/auth/CustomUserDetailService.java
  src/main/java/turing/turing/domain/auth/CustomUserDetails.java
  src/main/java/turing/turing/domain/auth/apple/AppleClient.java
  src/main/java/turing/turing/domain/auth/apple/ApplePublicKey.java
  src/main/java/turing/turing/domain/auth/apple/ApplePublicKeyGenerator.java
  src/main/java/turing/turing/domain/auth/apple/ApplePublicKeys.java
  src/main/java/turing/turing/domain/auth/apple/AppleTokenParser.java
  src/main/java/turing/turing/domain/auth/apple/VerifyAppleRequest.java
  src/main/java/turing/turing/domain/auth/dto/LoginRequest.java
  src/main/java/turing/turing/domain/auth/dto/LoginResponse.java
  src/main/java/turing/turing/domain/auth/dto/TokenReIssueRequest.java
  src/main/java/turing/turing/domain/auth/jwt/JwtTokenProvider.java
  src/main/java/turing/turing/domain/auth/jwt/TokenResponse.java
  src/main/java/turing/turing/domain/student/StudentRepository.java
  src/main/java/turing/turing/domain/teacher/TeacherController.java
  src/main/java/turing/turing/domain/teacher/TeacherRepository.java
  src/main/java/turing/turing/domain/teacher/TeacherService.java
  src/main/java/turing/turing/domain/teacher/dto/SignUpResponse.java
  src/main/java/turing/turing/domain/teacher/dto/TeacherSignUpRequest.java
  src/main/java/turing/turing/global/config/OpenFeignConfig.java
  src/main/java/turing/turing/global/config/SecurityConfig.java
  src/main/java/turing/turing/global/security/JwtAuthenticationFilter.java
Labels: ❕Hotfix

#19 [Feat] 알림장 CRUD 구현
  src/main/java/turing/turing/domain/TestController.java
  src/main/java/turing/turing/domain/homework/Homework.java
  src/main/java/turing/turing/domain/homework/HomeworkRepository.java
  src/main/java/turing/turing/domain/homework/converter/HomeworkConverter.java
  src/main/java/turing/turing/domain/homework/dto/HomeworkDto.java
  src/main/java/turing/turing/domain/notebook/Notebook.java
  src/main/java/turing/turing/domain/notebook/NotebookController.java
  src/main/java/turing/turing/domain/notebook/NotebookRepository.java
  src/main/java/turing/turing/domain/notebook/NotebookService.java
  src/main/java/turing/turing/domain/notebook/dto/CreateNotebookDto.java
  src/main/java/turing/turing/domain/notebook/dto/ModifyDeadlineDto.java
  src/main/java/turing/turing/domain/notebook/dto/NotebookInfo.java
  src/main/java/turing/turing/domain/schedule/ScheduleRepository.java
  src/main/java/turing/turing/domain/student/StudentRepository.java
  src/main/java/turing/turing/domain/studyRoom/StudyRoom.java
  src/main/java/turing/turing/domain/teacher/Teacher.java
  src/main/java/turing/turing/global/exception/GlobalExceptionHandler.java
  src/main/java/turing/turing/global/exception/errorCode/CommonErrorCode.java
  src/main/resources/application.yml
Labels: ⭐️ Feature

#32 [Feat] 질문게시판 도메인 기능 구현
  build.gradle
  src/main/java/turing/turing/domain/comment/Comment.java
  src/main/java/turing/turing/domain/comment/CommentController.java
  src/main/java/turing/turing/domain/comment/CommentRepository.java
  src/main/java/turing/turing/domain/comment/CommentService.java
  src/main/java/turing/turing/domain/comment/dto/request/CommentReqDto.java
  src/main/java/turing/turing/domain/comment/dto/response/CommentCreateResDto.java
  src/main/java/turing/turing/domain/comment/dto/response/CommentResDto.java
  src/main/java/turing/turing/domain/question/Question.java
  src/main/java/turing/turing/domain/question/QuestionController.java
  src/main/java/turing/turing/domain/question/QuestionRepository.java
  src/main/java/turing/turing/domain/question/QuestionService.java
  src/main/java/turing/turing/domain/question/dto/request/QuestionReqDto.java
  src/main/java/turing/turing/domain/question/dto/response/QuestionCreateResDto.java
  src/main/java/turing/turing/domain/question/dto/response/QuestionPreviewResDto.java
  src/main/java/turing/turing/domain/question/dto/response/QuestionWithCommentsResDto.java
  src/main/java/turing/turing/domain/student/StudentRepository.java
  src/main/java/turing/turing/domain/studyRoom/StudyRoomRepository.java
  src/main/java/turing/turing/domain/teacher/TeacherRepository.java
  src/main/java/turing/turing/global/config/S3Config.java
  src/main/java/turing/turing/global/s3/FileService.java
  src/main/java/turing/turing/global/s3/S3Component.java
  src/main/java/turing/turing/global/s3/S3Service.java
Labels: ⭐️ Feature

#35 [!Hotfix] s3 properties 추가
  src/main/resources/application.yml
Labels: ❕Hotfix

#38 [Feat] 질문 게시판 추가 기능 구현 및 API 명세 추가
  src/main/java/turing/turing/domain/auth/AuthController.java
  src/main/java/turing/turing/domain/comment/CommentController.java
  src/main/java/turing/turing/domain/homework/HomeworkController.java
  src/main/java/turing/turing/domain/notebook/NotebookController.java
  src/main/java/turing/turing/domain/question/Question.java
  src/main/java/turing/turing/domain/question/QuestionController.java
  src/main/java/turing/turing/domain/question/QuestionService.java
  src/main/java/turing/turing/domain/question/dto/request/QuestionReqDto.java
  src/main/java/turing/turing/domain/studyRoom/StudyRoomController.java
Labels: ⭐️ Feature

#44 [Feat] 카카오 로그인 API 구현
  src/main/java/turing/turing/domain/auth/AuthController.java
  src/main/java/turing/turing/domain/auth/AuthService.java
  src/main/java/turing/turing/domain/auth/CustomUserDetails.java
  src/main/java/turing/turing/domain/auth/apple/VerifyAppleRequest.java
  src/main/java/turing/turing/domain/auth/dto/LoginRequest.java
  src/main/java/turing/turing/domain/auth/dto/LoginResponse.java
  src/main/java/turing/turing/domain/auth/jwt/JwtTokenProvider.java
  src/main/java/turing/turing/domain/auth/kakao/VerifyKakaoRequest.java
  src/main/java/turing/turing/domain/member/Member.java
  src/main/java/turing/turing/domain/member/MemberController.java
  src/main/java/turing/turing/domain/member/MemberService.java
  src/main/java/turing/turing/domain/member/Provider.java
  src/main/java/turing/turing/domain/member/Role.java
  src/main/java/turing/turing/domain/member/dto/SignUpRequest.java
  src/main/java/turing/turing/domain/member/dto/SignUpResponse.java
  src/main/java/turing/turing/domain/question/QuestionService.java
  src/main/java/turing/turing/domain/student/Student.java
  src/main/java/turing/turing/domain/student/StudentRepository.java
  src/main/java/turing/turing/domain/teacher/Teacher.java
  src/main/java/turing/turing/domain/teacher/TeacherController.java
  src/main/java/turing/turing/domain/teacher/TeacherRepository.java
  src/main/java/turing/turing/domain/teacher/TeacherService.java
  src/main/java/turing/turing/domain/teacher/dto/TeacherSignUpRequest.java
  src/main/java/turing/turing/global/config/SecurityConfig.java
  src/main/java/turing/turing/global/security/JwtAuthenticationFilter.java
Labels: ⭐️ Feature

#7 [Feat] report CRUD
  .gitignore
  build.gradle
  src/main/java/turing/turing/domain/auth/AuthService.java
  src/main/java/turing/turing/domain/auth/dto/LoginResponse.java
  src/main/java/turing/turing/domain/gpt/GptService.java
  src/main/java/turing/turing/domain/gpt/PromptGenerator.java
  src/main/java/turing/turing/domain/gpt/dto/GPTRequest.java
  src/main/java/turing/turing/domain/gpt/dto/GPTResponse.java
  src/main/java/turing/turing/domain/gpt/dto/Message.java
  src/main/java/turing/turing/domain/member/MemberService.java
  src/main/java/turing/turing/domain/member/dto/SignUpRequest.java
  src/main/java/turing/turing/domain/notebook/NotebookRepository.java
  src/main/java/turing/turing/domain/notebook/NotebookService.java
  src/main/java/turing/turing/domain/notebook/dto/NotebookInfo.java
  src/main/java/turing/turing/domain/report/Report.java
  src/main/java/turing/turing/domain/report/ReportController.java
  src/main/java/turing/turing/domain/report/ReportRepository.java
  src/main/java/turing/turing/domain/report/ReportService.java
  src/main/java/turing/turing/domain/report/converter/ReportConverter.java
  src/main/java/turing/turing/domain/report/dto/ReportReadAllDto.java
  src/main/java/turing/turing/domain/report/dto/ReportReqDto.java
  src/main/java/turing/turing/domain/report/dto/ReportResDto.java
  src/main/java/turing/turing/domain/schedule/ScheduleRepository.java
  src/main/java/turing/turing/domain/studyRoom/StudyRoomRepository.java
  src/main/java/turing/turing/global/config/GPTConfig.java
  src/main/java/turing/turing/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: ⭐️ Feature

#50 Fix: report merge conflict
  src/main/java/turing/turing/domain/report/ReportRepository.java
  src/main/java/turing/turing/domain/report/ReportService.java
  src/main/java/turing/turing/domain/report/dto/ReportReadAllDto.java
  src/main/java/turing/turing/domain/studyRoom/StudyRoomRepository.java
  src/main/java/turing/turing/global/config/SecurityConfig.java
  src/main/java/turing/turing/global/exception/errorCode/CommonErrorCode.java
  src/main/resources/application.yml
Labels: 🛠️ Fix

#52 [Feat] 과외 공간 도메인 API 수정 및 @AuthenticationPrincipal 적용
  src/main/java/turing/turing/domain/code/ConnectionCodeRepository.java
  src/main/java/turing/turing/domain/studyRoom/StudyRoom.java
  src/main/java/turing/turing/domain/studyRoom/StudyRoomController.java
  src/main/java/turing/turing/domain/studyRoom/StudyRoomRepository.java
  src/main/java/turing/turing/domain/studyRoom/StudyRoomService.java
  src/main/java/turing/turing/domain/studyRoom/dto/StudyRoomResDto.java
  src/main/java/turing/turing/domain/studyRoom/dto/request/StudyRoomCreateReqDto.java
  src/main/java/turing/turing/domain/studyRoom/dto/request/StudyRoomUpdateReqDto.java
  src/main/java/turing/turing/domain/studyRoom/dto/response/DetailedStudyRoomResDto.java
  src/main/java/turing/turing/domain/studyRoom/dto/response/StudyRoomResDto.java
  src/main/java/turing/turing/domain/studyRoom/dto/response/SubjectAndTeacherResDto.java
Labels: ⭐️ Feature, 🛠️ Fix

#40 [Feat] 스케줄 CRUD 구현
  src/main/java/turing/turing/domain/alternativeSchedule/AlternativeController.java
  src/main/java/turing/turing/domain/alternativeSchedule/AlternativeSchedule.java
  src/main/java/turing/turing/domain/alternativeSchedule/AlternativeScheduleRepository.java
  src/main/java/turing/turing/domain/alternativeSchedule/AlternativeService.java
  src/main/java/turing/turing/domain/alternativeSchedule/converter/AlterScheduleConverter.java
  src/main/java/turing/turing/domain/alternativeSchedule/dto/AllAlterSchedules.java
  src/main/java/turing/turing/domain/alternativeSchedule/dto/AlterScheduleDto.java
  src/main/java/turing/turing/domain/alternativeSchedule/dto/CreateAlterScheduleRequest.java
  src/main/java/turing/turing/domain/alternativeSchedule/dto/CreateAlterScheduleResponse.java
  src/main/java/turing/turing/domain/alternativeSchedule/dto/TimePairDto.java
  src/main/java/turing/turing/domain/alternativeSchedule/dto/ToAlterScheduleDto.java
  src/main/java/turing/turing/domain/exam/Exam.java
  src/main/java/turing/turing/domain/exam/ExamController.java
  src/main/java/turing/turing/domain/exam/ExamRepository.java
  src/main/java/turing/turing/domain/exam/ExamService.java
  src/main/java/turing/turing/domain/exam/converter/ExamConverter.java
  src/main/java/turing/turing/domain/exam/dto/CreateExamRequest.java
  src/main/java/turing/turing/domain/exam/dto/CreateExamResponse.java
  src/main/java/turing/turing/domain/exam/dto/ExamDto.java
  src/main/java/turing/turing/domain/notice/dto/BaseNoticeInfo.java
  src/main/java/turing/turing/domain/schedule/Schedule.java
  src/main/java/turing/turing/domain/schedule/ScheduleController.java
  src/main/java/turing/turing/domain/schedule/ScheduleRepository.java
  src/main/java/turing/turing/domain/schedule/ScheduleService.java
  src/main/java/turing/turing/domain/schedule/dto/CreateScheduleRequest.java
  src/main/java/turing/turing/domain/schedule/dto/ModifyScheduleRequest.java
  src/main/java/turing/turing/domain/schedule/dto/ScheduleDto.java
  src/main/java/turing/turing/domain/schedule/dto/UpdateScheduleDto.java
  src/main/java/turing/turing/domain/studyRoom/StudyRoom.java
  src/main/java/turing/turing/domain/studyRoom/StudyRoomController.java
  src/main/java/turing/turing/domain/studyRoom/StudyRoomService.java
  src/main/java/turing/turing/domain/studyRoom/dto/BaseTemplateDto.java
  src/main/java/turing/turing/domain/studyTime/StudyTimeRepository.java
Labels: ⭐️ Feature

#55 [Fix] 과외공간, 질문게시판 등 수정 사항 반영 및 예외 코드 등록
  src/main/java/turing/turing/domain/alternativeSchedule/dto/CreateAlterScheduleResponse.java
  src/main/java/turing/turing/domain/auth/AuthService.java
  src/main/java/turing/turing/domain/auth/dto/LoginRequest.java
  src/main/java/turing/turing/domain/comment/CommentService.java
  src/main/java/turing/turing/domain/exam/dto/CreateExamResponse.java
  src/main/java/turing/turing/domain/member/Member.java
  src/main/java/turing/turing/domain/member/MemberService.java
  src/main/java/turing/turing/domain/notebook/NotebookService.java
  src/main/java/turing/turing/domain/notebook/dto/NotebookInfo.java
  src/main/java/turing/turing/domain/notice/dto/BaseNoticeInfo.java
  src/main/java/turing/turing/domain/question/Question.java
  src/main/java/turing/turing/domain/question/QuestionController.java
  src/main/java/turing/turing/domain/question/QuestionRepository.java
  src/main/java/turing/turing/domain/question/QuestionService.java
  src/main/java/turing/turing/domain/question/dto/response/QuestionPreviewResDto.java
  src/main/java/turing/turing/domain/question/dto/response/QuestionWithCommentsResDto.java
  src/main/java/turing/turing/domain/report/ReportRepository.java
  src/main/java/turing/turing/domain/report/dto/ReportReadAllDto.java
  src/main/java/turing/turing/domain/schedule/Schedule.java
  src/main/java/turing/turing/domain/studyRoom/StudyRoomController.java
  src/main/java/turing/turing/domain/studyRoom/StudyRoomService.java
  src/main/java/turing/turing/global/exception/errorCode/QuestionErrorCode.java
  src/main/java/turing/turing/global/exception/errorCode/StudyRoomErrorCode.java
  src/main/java/turing/turing/global/exception/errorCode/UserErrorCode.java
Labels: ⭐️ Feature, 🛠️ Fix

#53 [Feat] Redis 사용하여 RefreshToken 관리 & 회원탈퇴 구현
  build.gradle
  src/main/java/turing/turing/domain/auth/AuthService.java
  src/main/java/turing/turing/domain/auth/jwt/JwtTokenProvider.java
  src/main/java/turing/turing/domain/member/MemberController.java
  src/main/java/turing/turing/domain/member/MemberService.java
  src/main/java/turing/turing/global/RedisConfig.java
  src/main/java/turing/turing/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: ⭐️ Feature

#80 [Fix] LocalTime DTO에 @JsonFormat 적용
  src/main/java/turing/turing/domain/alternativeSchedule/dto/AlterScheduleDto.java
  src/main/java/turing/turing/domain/alternativeSchedule/dto/TimePairDto.java
  src/main/java/turing/turing/domain/schedule/ScheduleService.java
  src/main/java/turing/turing/domain/schedule/dto/ModifyScheduleRequest.java
  src/main/java/turing/turing/domain/schedule/dto/ScheduleDto.java
  src/main/java/turing/turing/domain/schedule/dto/UpdateScheduleDto.java
Labels: 🛠️ Fix

#85 [Fix] 학생 연결 시 학교, 학년 정보를 동기화하도록 수정
  src/main/java/turing/turing/domain/student/Student.java
  src/main/java/turing/turing/domain/studyRoom/StudyRoomService.java
Labels: 🛠️ Fix

#83 [Fix]: 요청의 시작요일을 앞으로의 첫 일정시작 요일로 수정
  src/main/java/turing/turing/domain/schedule/ScheduleService.java
Labels: 🛠️ Fix

#87 [Fix]: 자동로그인 시 필터를 거쳐서 토큰의 정보를 사용하도록 수정
  src/main/java/turing/turing/domain/auth/AuthController.java
  src/main/java/turing/turing/domain/auth/AuthService.java
  src/main/java/turing/turing/domain/auth/dto/LoginRequest.java
  src/main/java/turing/turing/domain/auth/dto/LoginResponse.java
  src/main/java/turing/turing/global/config/SecurityConfig.java
Labels: 🛠️ Fix

#101 [Fix] AccessToken 재발급 요청의 json body 값 읽지 못하는 버그 해결 & AppleIdToken에서 email 추출 로직 이전으로 복구
  src/main/java/turing/turing/domain/auth/AuthService.java
  src/main/java/turing/turing/domain/auth/apple/AppleTokenParser.java
  src/main/java/turing/turing/domain/auth/dto/TokenReIssueRequest.java
Labels: 🛠️ Fix

#97 [Fix] 학생의 '회원 탈퇴'의 경우 '학생 연결 해제' 로직 적용 & cascade 옵션 제거
  src/main/java/turing/turing/domain/member/MemberService.java
  src/main/java/turing/turing/domain/question/Question.java
  src/main/java/turing/turing/domain/question/QuestionRepository.java
  src/main/java/turing/turing/domain/question/QuestionService.java
  src/main/java/turing/turing/domain/question/dto/response/QuestionWithCommentsResDto.java
  src/main/java/turing/turing/domain/studyRoom/StudyRoom.java
  src/main/java/turing/turing/domain/studyRoom/StudyRoomRepository.java
Labels: 🛠️ Fix

#104 [Fix] Student 엔티티의 fcm_token 중복 필드 제거
  src/main/java/turing/turing/domain/auth/CustomUserDetailService.java
  src/main/java/turing/turing/domain/notebook/NotebookController.java
  src/main/java/turing/turing/domain/student/Student.java
Labels: ❕Hotfix
