Repository Turing-mentos/Turing-BE, pull requests merged in 2024-06, with the labels that each got.

#6 [Fix] CSRF 검증 비활성화
  src/main/java/turing/turing/global/config/SecurityConfig.java
Labels: 🐞 Bug

#4 [Feat] 숙제 CRUD 구현
  .github/PULL_REQUEST_TEMPLATE.md
  src/main/java/turing/turing/domain/BaseEntity.java
  src/main/java/turing/turing/domain/TestController.java
  src/main/java/turing/turing/domain/homework/Homework.java
  src/main/java/turing/turing/domain/homework/HomeworkController.java
  src/main/java/turing/turing/domain/homework/HomeworkRepository.java
  src/main/java/turing/turing/domain/homework/HomeworkService.java
  src/main/java/turing/turing/domain/homework/converter/HomeworkConverter.java
  src/main/java/turing/turing/domain/homework/dto/DetailedHomeworkDto.java
  src/main/java/turing/turing/domain/notebook/NotebookRepository.java
Labels: ⭐️ Feature

#11 [Fix] 누락된 연관관계 추가
  src/main/java/turing/turing/domain/question/Question.java
  src/main/java/turing/turing/domain/schedule/Schedule.java
  src/main/java/turing/turing/domain/studyRoom/StudyRoom.java
Labels: ❕Hotfix

#16 fix: ERD 수정에 따른 변경 사항 반영
  src/main/java/turing/turing/domain/comment/Comment.java
  src/main/java/turing/turing/domain/report/Report.java
  src/main/java/turing/turing/domain/student/Student.java
  src/main/java/turing/turing/domain/teacher/Teacher.java
Labels: 🛠️ Fix
